<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Accessory extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Accessory_model');
    } 

    /*
     * Listing of accessories
     */
    function index()
    {
        $data['accessories'] = $this->Accessory_model->get_all_accessories();
        
        $data['_view'] = 'accessory/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new accessory
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('name','Name','alpha_numeric');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'category_id' => $this->input->post('category_id'),
				'name' => $this->input->post('name'),
            );
            
            $accessory_id = $this->Accessory_model->add_accessory($params);
            redirect('accessory/index');
        }
        else
        {
			$this->load->model('Category_model');
			$data['all_categories'] = $this->Category_model->get_all_categories();
            
            $data['_view'] = 'accessory/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a accessory
     */
    function edit($id)
    {   
        // check if the accessory exists before trying to edit it
        $data['accessory'] = $this->Accessory_model->get_accessory($id);
        
        if(isset($data['accessory']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('name','Name','alpha_numeric');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'category_id' => $this->input->post('category_id'),
					'name' => $this->input->post('name'),
                );

                $this->Accessory_model->update_accessory($id,$params);            
                redirect('accessory/index');
            }
            else
            {
				$this->load->model('Category_model');
				$data['all_categories'] = $this->Category_model->get_all_categories();

                $data['_view'] = 'accessory/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The accessory you are trying to edit does not exist.');
    } 

    /*
     * Deleting accessory
     */
    function remove($id)
    {
        $accessory = $this->Accessory_model->get_accessory($id);

        // check if the accessory exists before trying to delete it
        if(isset($accessory['id']))
        {
            $this->Accessory_model->delete_accessory($id);
            redirect('accessory/index');
        }
        else
            show_error('The accessory you are trying to delete does not exist.');
    }
    
}
