<?php

/*
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Color extends CI_Controller
{
    function __construct() {
        parent::__construct();
        $this->load->model('Color_model');
    }

    /*
     * Listing of colors
     */
    function index() {
        $data['colors'] = $this->Color_model->get_all_colors();

        $data['_view'] = 'color/index';
        $this->load->view('layouts/main', $data);
    }

    /*
     * Adding a new color
     */
    function add() {
        $this->load->library('form_validation');

        $this->form_validation->set_rules('name', 'Name', 'is_unique[colors.name]|max_length[50]|alpha');

        if ($this->form_validation->run()) {
            $params = array(
                'name' => $this->input->post('name'),
            );

            $color_id = $this->Color_model->add_color($params);
            redirect('color/index');
        } else {
            $data['_view'] = 'color/add';
            $this->load->view('layouts/main', $data);
        }
    }

    /*
     * Editing a color
     */
    function edit($id) {
        // check if the color exists before trying to edit it
        $data['color'] = $this->Color_model->get_color($id);

        if (isset($data['color']['id'])) {
            $this->load->library('form_validation');

            $this->form_validation->set_rules('name', 'Name', 'callback_check_name|max_length[50]|alpha');

            if ($this->form_validation->run()) {
                $params = array(
                    'name' => $this->input->post('name'),
                );

                $this->Color_model->update_color($id, $params);
                redirect('color/index');
            } else {
                $data['_view'] = 'color/edit';
                $this->load->view('layouts/main', $data);
            }
        } else
            show_error('The color you are trying to edit does not exist.');
    }

    /*
     * Deleting color
     */
    function remove($id) {
        $color = $this->Color_model->get_color($id);

        // check if the color exists before trying to delete it
        if (isset($color['id'])) {
            $this->Color_model->delete_color($id);
            redirect('color/index');
        } else
            show_error('The color you are trying to delete does not exist.');
    }

    /**
     * @param string $id
     * @param $name
     * @return bool
     */
    function check_name($id = '', $name) {
        $this->db->where('name', $name);
        if ($id) {
            $this->db->where_not_in('id', $id);
        }
        return count($this->db->get('colors')->num_rows()) > 0 ? true : false;
    }

}
