<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Option extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Option_model');
    } 

    /*
     * Listing of options
     */
    function index()
    {
        $data['options'] = $this->Option_model->get_all_options();
        
        $data['_view'] = 'option/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new option
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('name','Name','required|max_length[50]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'category_id' => $this->input->post('category_id'),
				'name' => $this->input->post('name'),
            );
            
            $option_id = $this->Option_model->add_option($params);
            redirect('option/index');
        }
        else
        {
			$this->load->model('Category_model');
			$data['all_categories'] = $this->Category_model->get_all_categories();
            
            $data['_view'] = 'option/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a option
     */
    function edit($id)
    {   
        // check if the option exists before trying to edit it
        $data['option'] = $this->Option_model->get_option($id);
        
        if(isset($data['option']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('name','Name','required|max_length[50]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'category_id' => $this->input->post('category_id'),
					'name' => $this->input->post('name'),
                );

                $this->Option_model->update_option($id,$params);            
                redirect('option/index');
            }
            else
            {
				$this->load->model('Category_model');
				$data['all_categories'] = $this->Category_model->get_all_categories();

                $data['_view'] = 'option/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The option you are trying to edit does not exist.');
    } 

    /*
     * Deleting option
     */
    function remove($id)
    {
        $option = $this->Option_model->get_option($id);

        // check if the option exists before trying to delete it
        if(isset($option['id']))
        {
            $this->Option_model->delete_option($id);
            redirect('option/index');
        }
        else
            show_error('The option you are trying to delete does not exist.');
    }
    
}
