<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Accessory_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get accessory by id
     */
    function get_accessory($id)
    {
        return $this->db->get_where('accessories',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all accessories
     */
    function get_all_accessories()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('accessories')->result_array();
    }
        
    /*
     * function to add new accessory
     */
    function add_accessory($params)
    {
        $this->db->insert('accessories',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update accessory
     */
    function update_accessory($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('accessories',$params);
    }
    
    /*
     * function to delete accessory
     */
    function delete_accessory($id)
    {
        return $this->db->delete('accessories',array('id'=>$id));
    }
}
