<?php

/*
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Brand_model extends CI_Model
{
    function __construct() {
        parent::__construct();
    }

    /*
     * Get brand by id
     */
    function get_brand($id) {
        return $this->db->get_where('brands', array('id' => $id))->row_array();
    }

    /*
     * Get all brands
     */
    function get_all_brands() {
        $this->db->order_by('name', 'asc');
        return $this->db->get('brands')->result_array();
    }

    /*
     * function to add new brand
     */
    function add_brand($params) {
        $this->db->insert('brands', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update brand
     */
    function update_brand($id, $params) {
        $this->db->where('id', $id);
        return $this->db->update('brands', $params);
    }

    /*
     * function to delete brand
     */
    function delete_brand($id) {
        return $this->db->delete('brands', array('id' => $id));
    }
}
