<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Color_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get color by id
     */
    function get_color($id)
    {
        return $this->db->get_where('colors',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all colors
     */
    function get_all_colors()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('colors')->result_array();
    }
        
    /*
     * function to add new color
     */
    function add_color($params)
    {
        $this->db->insert('colors',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update color
     */
    function update_color($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('colors',$params);
    }
    
    /*
     * function to delete color
     */
    function delete_color($id)
    {
        return $this->db->delete('colors',array('id'=>$id));
    }
}
