<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Color_category_map_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get color_category_map by 
     */
    function get_color_category_map($)
    {
        return $this->db->get_where('color_category_map',array(''=>$))->row_array();
    }
        
    /*
     * Get all color_category_map
     */
    function get_all_color_category_map()
    {
        $this->db->order_by('', 'desc');
        return $this->db->get('color_category_map')->result_array();
    }
        
    /*
     * function to add new color_category_map
     */
    function add_color_category_map($params)
    {
        $this->db->insert('color_category_map',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update color_category_map
     */
    function update_color_category_map($,$params)
    {
        $this->db->where('',$);
        return $this->db->update('color_category_map',$params);
    }
    
    /*
     * function to delete color_category_map
     */
    function delete_color_category_map($)
    {
        return $this->db->delete('color_category_map',array(''=>$));
    }
}
