<?php

/*
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Condition_model extends CI_Model
{
    function __construct() {
        parent::__construct();
    }

    /*
     * Get condition by id
     */
    function get_condition($id) {
        return $this->db->get_where('conditions', array('id' => $id))->row_array();
    }

    /*
     * Get all conditions
     */
    function get_all_conditions() {
        $this->db->order_by('id', 'desc');
        return $this->db->get('conditions')->result_array();
    }

    /*
     * function to add new condition
     */
    function add_condition($params) {
        $this->db->insert('conditions', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update condition
     */
    function update_condition($id, $params) {
        $this->db->where('id', $id);
        return $this->db->update('conditions', $params);
    }

    /*
     * function to delete condition
     */
    function delete_condition($id) {
        return $this->db->delete('conditions', array('id' => $id));
    }
}
