<?php

/*
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Option_model extends CI_Model
{
    function __construct() {
        parent::__construct();
    }

    /*
     * Get option by id
     */
    function get_option($id) {
        return $this->db->get_where('options', array('id' => $id))->row_array();
    }

    /*
     * Get all options
     */
    function get_all_options() {
        $this->db->select('options.*, categories.name AS category');
        $this->db->join('categories', 'options.category_id = categories.id', 'LEFT');
        $this->db->order_by('options.id', 'desc');
        return $this->db->get('options')->result_array();
    }

    /**
     * @param $category_id
     * @return mixed
     */
    function get_options_of_category($category_id) {
        return $this->db->where('category_id', $category_id)
            ->get('options')
            ->result_array();
    }

    /*
     * function to add new option
     */
    function add_option($params) {
        $this->db->insert('options', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update option
     */
    function update_option($id, $params) {
        $this->db->where('id', $id);
        return $this->db->update('options', $params);
    }

    /*
     * function to delete option
     */
    function delete_option($id) {
        return $this->db->delete('options', array('id' => $id));
    }
}
