<?php

/*
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Permission_map_model extends CI_Model
{
    function __construct() {
        parent::__construct();
    }

    /*
     * Get permission_map by groupID
     */
    function get_permission_map($groupID) {
        return $this->db->get_where('permission_map', array('groupID' => $groupID))->row_array();
    }

    /*
     * Get all permission_map
     */
    function get_all_permission_map() {
        return $this->db->select('permission_map.*, permission_groups.name, permissions.permission')
            ->join('permission_groups', 'permission_map.groupID = permission_groups.id', 'INNER')
            ->join('permissions', 'permission_map.permissionID = permissions.permissionID', 'INNER')
            ->order_by('permission_groups.name', 'asc')
            ->get('permission_map')
            ->result_array();
    }

    /*
     * function to add new permission_map
     */
    function add_permission_map($params) {
        $this->db->insert('permission_map', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update permission_map
     */
    function update_permission_map($groupID, $params) {
        $this->db->where('groupID', $groupID);
        return $this->db->update('permission_map', $params);
    }

    /*
     * function to delete permission_map
     */
    function delete_permission_map($groupID) {
        return $this->db->delete('permission_map', array('groupID' => $groupID));
    }
}
