<?php

/*
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Permission_group_model extends CI_Model
{
    function __construct() {
        parent::__construct();
    }

    /*
     * Get permission_group by id
     */
    function get_permission_group($id) {
        return $this->db->get_where('permission_groups', array('id' => $id))->row_array();
    }

    /*
     * Get all permission_groups
     */
    function get_all_permission_groups() {
        $this->db->order_by('id', 'desc');
        return $this->db->get('permission_groups')->result_array();
    }

    /*
     * function to add new permission_group
     */
    function add_permission_group($params) {
        $this->db->insert('permission_groups', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update permission_group
     */
    function update_permission_group($id, $params) {
        $this->db->where('id', $id);
        return $this->db->update('permission_groups', $params);
    }

    /*
     * function to delete permission_group
     */
    function delete_permission_group($id) {
        return $this->db->delete('permission_groups', array('id' => $id));
    }
}
