<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Product_picture_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get product_picture by id
     */
    function get_product_picture($id)
    {
        return $this->db->get_where('product_pictures',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all product_pictures
     */
    function get_all_product_pictures()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('product_pictures')->result_array();
    }
        
    /*
     * function to add new product_picture
     */
    function add_product_picture($params)
    {
        $this->db->insert('product_pictures',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update product_picture
     */
    function update_product_picture($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('product_pictures',$params);
    }
    
    /*
     * function to delete product_picture
     */
    function delete_product_picture($id)
    {
        return $this->db->delete('product_pictures',array('id'=>$id));
    }
}
