<?php

/*
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Product_picture_model extends CI_Model
{
    const PICTURE_TYPES = [
        'profile_pic' => 1,
        'open_pic' => 2,
        'display_pic' => 3,
        'measurement_tracking_pic' => 4,
        'power_src_pic' => 5,
        'damage_pic' => 6,
        'missing_pieces_pic' => 7,
        'descriptive_pic' => 8,
        'model_serial_no_pic' => 9
    ];

    function __construct() {
        parent::__construct();
    }

    /*
     * Get product_picture by id
     */
    function get_product_picture($id) {
        return $this->db->get_where('product_pictures', array('id' => $id))->row_array();
    }

    /*
     * Get all product_pictures
     */
    function get_all_product_pictures() {
        $this->db->order_by('id', 'desc');
        return $this->db->get('product_pictures')->result_array();
    }

    /*
     * function to add new product_picture
     */
    function add_product_picture($params) {
        $this->db->insert('product_pictures', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update product_picture
     */
    function update_product_picture($id, $params) {
        $this->db->where('id', $id);
        return $this->db->update('product_pictures', $params);
    }

    /*
     * function to delete product_picture
     */
    function delete_product_picture($id) {
        return $this->db->delete('product_pictures', array('id' => $id));
    }

    /**
     * @param $product_id
     * @param $arr_pics
     */
    function save_pictures($product_id, $arr_pics) {
        foreach($arr_pics as $type => $file_names) {
            foreach($file_names as $name) {
                $this->db->insert('product_pictures', [
                    'product_id' => $product_id,
                    'type' => $type,
                    'name' => $name,
                ]);
            }
        }
    }
}
